# Generated by Django 5.2.6 on 2025-11-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='laste_name',
            new_name='last_name',
        ),
    ]
